### PR TITLE
7-test-fix

### LINKED ISSUE #14: Fix all tests
### ProjectDTOConverterTest
You need to autowire ProjectDTOConverter using Spring

### PR DESCRIPTION
**Pull request by vanyaserdyuk**

### CODE REVIEW

File: src/main/java/ru/testtask/model/Project.java [hunk 1]
```diff
@@ -17,6 +17,7 @@
 
     @Id
     @Getter
+    @Setter
```
Comment (iv21dk) [inline src/main/java/ru/testtask/model/Project.java]: All fields has getters and setters. You can remove all annotations `@Getter` and `@Setter` and use `@Data` instead

File: src/test/java/ru/testtask/converter/ProjectDTOConverterTest.java [hunk 2]
```diff
@@ -25,10 +27,14 @@
...
+@SpringBootTest(classes = {Application.class})
 public class ProjectDTOConverterTest {
     @Autowired
     private ProjectDTOConverter projectDTOConverter;
 
+    @Mock
+    private UserService userService;
+
     @Autowired
     private DTOConverterConfig modelMapper;
```
Comment (iv21dk) [inline src/test/java/ru/testtask/converter/ProjectDTOConverterTest.java]: It is unused field, you can remove it

File: src/test/java/ru/testtask/service/ProjectServiceTest.java [hunk 3]
```diff
@@ -1,43 +1,54 @@
...
-    private static Project testProject;
+    @MockBean
+    private UserService userService;
 
-    @Mock
-    private static ProjectRepo projectRepo;
+    private Project testProject;
+
+    @Autowired
+    private ProjectRepo projectRepo;
```
Comment (iv21dk) [inline src/test/java/ru/testtask/service/ProjectServiceTest.java]: You can remove unused field

File: src/test/java/ru/testtask/service/ProjectServiceTest.java [hunk 4]
```diff
@@ -1,43 +1,54 @@
...
 
-    @Before
-    public void initService(){
-         projectService = new ProjectService();
-    }
-
-    @Test
+    @Test()
     public void createTest(){
         Project resultProject = projectService.createProject(testProject);
```
Comment (iv21dk) [inline src/test/java/ru/testtask/service/ProjectServiceTest.java]: You need to remove all projects before, because the test will be failed if project already exist

File: src/test/java/ru/testtask/service/ProjectServiceTest.java [hunk 5]
```diff
@@ -1,43 +1,54 @@
...
 import java.util.List;
 
 import static org.junit.Assert.*;
+import static org.mockito.ArgumentMatchers.any;
+import static org.mockito.ArgumentMatchers.anyString;
 
 
 @RunWith(SpringRunner.class)
+@SpringBootTest(classes = {Application.class})
 public class ProjectServiceTest {
```
Comment (iv21dk) [inline src/test/java/ru/testtask/service/ProjectServiceTest.java:27]: Please add new test method to check `ProjectService#isCurrentUserOwnerOf(String id)`

File: src/test/java/ru/testtask/service/ProjectServiceTest.java [hunk 6]
```diff
@@ -57,6 +68,7 @@ public void createTest(){
 
     @Test(expected = NameAlreadyExistsException.class)
     public void checkSimilarNamesCreationTest(){
```
Comment (iv21dk) [inline src/test/java/ru/testtask/service/ProjectServiceTest.java]: You need to remove all projects before, because the test will be failed if project already exist

**Review by iv21dk — CHANGES_REQUESTED** [review]

File: src/test/java/ru/testtask/service/ProjectServiceTest.java [hunk 7]
```diff
@@ -60,4 +73,11 @@ public void checkSimilarNamesCreationTest(){
         Project resultProject = projectService.createProject(testProject);
         Project resultProject2 = projectService.createProject(testProject);
     }
+
+    @Test
+    public void isCurrentUserOwnerOfTest(){
```
Comment (iv21dk) [inline src/test/java/ru/testtask/service/ProjectServiceTest.java:74]: The test is failed. You need to use project id as parameter of method `projectService.isCurrentUserOwnerOf("a")`.

**Review by iv21dk — CHANGES_REQUESTED** [review]

File: src/main/resources/application.properties [hunk 8]
```diff
@@ -1,2 +0,0 @@
-spring.data.mongodb.database=Projects
```
Comment (iv21dk) [inline src/main/resources/application.properties]: I don't see reason to remove this file

**Review by iv21dk — CHANGES_REQUESTED** [review]

**Comment by iv21dk** [comment]
Approved
